2024-07-30 13:30:22 ERROR Traceback (most recent call last):
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/cli/cli.py", line 252, in login
    wandb.login(
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 84, in login
    configured = _login(
                 ^^^^^^^
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 346, in _login
    wlogin.prompt_api_key()
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 280, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

2024-07-30 13:32:10 ERROR Traceback (most recent call last):
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/cli/cli.py", line 252, in login
    wandb.login(
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 84, in login
    configured = _login(
                 ^^^^^^^
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 346, in _login
    wlogin.prompt_api_key()
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 280, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

2024-07-30 13:34:17 ERROR Traceback (most recent call last):
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/cli/cli.py", line 252, in login
    wandb.login(
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 84, in login
    configured = _login(
                 ^^^^^^^
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 346, in _login
    wlogin.prompt_api_key()
  File "/work/tc064/tc064/s2517783/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 280, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

